<template><div><h1 id="_4-1-树" tabindex="-1"><a class="header-anchor" href="#_4-1-树" aria-hidden="true">#</a> 4.1 树</h1>
<h2 id="_4-1-1-树的定义" tabindex="-1"><a class="header-anchor" href="#_4-1-1-树的定义" aria-hidden="true">#</a> 4.1.1 树的定义：</h2>
<p><code v-pre>树</code>是η(n≥0)个结点的有限集合,n≡o时,称为空树,这是一种特殊情况。在任意一棵非空树中应满足:
①有且仅有一个特定的称为根的<code v-pre>结点</code>。
②当n&gt;1时,其余结点可分为m(m&gt;0)个互不相交的有限集合T1,T2…,Tn,其中每个集合本身又是一棵树,并且称为根结点的<code v-pre>子树</code>。</p>
<figure><img src="/images/datastruct/20180801094313847.jfif" alt="img" tabindex="0" loading="lazy"><figcaption>img</figcaption></figure>
<h2 id="_4-1-2-树的术语" tabindex="-1"><a class="header-anchor" href="#_4-1-2-树的术语" aria-hidden="true">#</a> 4.1.2 树的术语</h2>
<p><code v-pre>父结点</code>：若一个结点含有子结点，则这个结点称为其子结点的父结点
<code v-pre>子结点</code>：一个结点含有的子树的根结点称为该结点的子结点
<code v-pre>兄弟结点</code>：拥有共同父结点的结点互称为兄弟结点
<code v-pre>祖先</code>：对任意结点x，从根结点到结点x的所有结点都是x的祖先（结点x也是自己的祖先）
<code v-pre>后代</code>：对任意结点x，从结点x到叶子结点的所有结点都是x的后代（结点x也是自己的后代）</p>
<p><code v-pre>两结点的路径</code>：对任意结点x，从结点x到结点y的<code v-pre>从上到下</code>的路
<code v-pre>两结点的路径长度</code>：对任意结点x，从结点x到结点y经过的边数</p>
<p><code v-pre>结点的层次</code>：对任意结点x，从根结点到结点x的<code v-pre>从上到下</code>经过的边数
<code v-pre>结点高度</code>：对任意结点x，叶子结点到x结点的路径长度就是结点x的<code v-pre>高度</code>
<code v-pre>树的深度</code>：一棵树中结点的最大深度就是树的深度，也称为<code v-pre>高度</code></p>
<p><code v-pre>结点的度</code>：有几个子结点（分支）
<code v-pre>树的度</code>：各结点的度的最大值
<code v-pre>叶子结点</code>：度为零的结点就是叶子结点</p>
<p><code v-pre>森林</code>：m颗互不相交的树构成的集合就是森林</p>
<h2 id="_4-2-3-树的分类" tabindex="-1"><a class="header-anchor" href="#_4-2-3-树的分类" aria-hidden="true">#</a> 4.2.3 树的分类</h2>
<p>有序树和无序树</p>
<p><code v-pre>有序树</code>一一逻辑上看，树中结点的各子树从左至右是有次序的，不能互换</p>
<p><code v-pre>无序树</code>一一逻辑上看，树中结点的各子树从左至右是无次序的，可以互换</p>
<h2 id="_4-2-4-树的性质" tabindex="-1"><a class="header-anchor" href="#_4-2-4-树的性质" aria-hidden="true">#</a> 4.2.4 树的性质</h2>
<p>考点1：结点数=总度数+1</p>
<p>考点2：度为m的树和m叉树
<code v-pre>度为m的树</code>：至少有一个结点度=m，一定是非空树
<code v-pre>m叉树</code>：允许所有结点的度都≤m，可以是空树</p>
<p>考点3：度为m的树第i层至多有几个结点？	<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msup><mi>m</mi><mrow><mi>i</mi><mo>−</mo><mn>1</mn></mrow></msup></mrow><annotation encoding="application/x-tex">m^{i-1}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8247em;"></span><span class="mord"><span class="mord mathnormal">m</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.8247em;"><span style="top:-3.063em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight">i</span><span class="mbin mtight">−</span><span class="mord mtight">1</span></span></span></span></span></span></span></span></span></span></span></span></p>
<p>考点4：高度为h的m叉树至多有几个结点？	<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mfrac><mrow><mo stretchy="false">(</mo><msup><mi>m</mi><mi>h</mi></msup><mo>−</mo><mn>1</mn><mo stretchy="false">)</mo></mrow><mrow><mo stretchy="false">(</mo><mi>m</mi><mo>−</mo><mn>1</mn><mo stretchy="false">)</mo></mrow></mfrac></mrow><annotation encoding="application/x-tex">\frac{(m^{h}-1)}{(m-1)}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.6539em;vertical-align:-0.52em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:1.1339em;"><span style="top:-2.655em;"><span class="pstrut" style="height:3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mopen mtight">(</span><span class="mord mathnormal mtight">m</span><span class="mbin mtight">−</span><span class="mord mtight">1</span><span class="mclose mtight">)</span></span></span></span><span style="top:-3.23em;"><span class="pstrut" style="height:3em;"></span><span class="frac-line" style="border-bottom-width:0.04em;"></span></span><span style="top:-3.485em;"><span class="pstrut" style="height:3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mopen mtight">(</span><span class="mord mtight"><span class="mord mathnormal mtight">m</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.927em;"><span style="top:-2.931em;margin-right:0.0714em;"><span class="pstrut" style="height:2.5em;"></span><span class="sizing reset-size3 size1 mtight"><span class="mord mtight"><span class="mord mathnormal mtight">h</span></span></span></span></span></span></span></span></span><span class="mbin mtight">−</span><span class="mord mtight">1</span><span class="mclose mtight">)</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.52em;"><span></span></span></span></span></span><span class="mclose nulldelimiter"></span></span></span></span></span></p>
<p>考点5：
高度为h的m叉树至少有多少个结点？	<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>h</mi></mrow><annotation encoding="application/x-tex">h</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6944em;"></span><span class="mord mathnormal">h</span></span></span></span></p>
<p>高度为h、度为m的树至少有多少个结点？		<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>h</mi><mo>+</mo><mi>m</mi><mo>−</mo><mn>1</mn></mrow><annotation encoding="application/x-tex">h+m-1</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.7778em;vertical-align:-0.0833em;"></span><span class="mord mathnormal">h</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6667em;vertical-align:-0.0833em;"></span><span class="mord mathnormal">m</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">1</span></span></span></span></p>
<p>考点6：具有n个结点的m叉树的最小高度为？	<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>l</mi><mi>o</mi><msub><mi>g</mi><mi>m</mi></msub><mo stretchy="false">⌈</mo><mo stretchy="false">(</mo><mi>n</mi><mo stretchy="false">(</mo><mi>m</mi><mo>−</mo><mn>1</mn><mo stretchy="false">)</mo><mo>+</mo><mn>1</mn><mo stretchy="false">)</mo><mo stretchy="false">⌉</mo></mrow><annotation encoding="application/x-tex">log_m\lceil (n(m-1)+1) \rceil</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.01968em;">l</span><span class="mord mathnormal">o</span><span class="mord"><span class="mord mathnormal" style="margin-right:0.03588em;">g</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.1514em;"><span style="top:-2.55em;margin-left:-0.0359em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight">m</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span><span class="mopen">⌈(</span><span class="mord mathnormal">n</span><span class="mopen">(</span><span class="mord mathnormal">m</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">1</span><span class="mclose">)</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">1</span><span class="mclose">)⌉</span></span></span></span></p>
</div></template>


