<template><div><h1 id="_5-2-图的存储结构" tabindex="-1"><a class="header-anchor" href="#_5-2-图的存储结构" aria-hidden="true">#</a> 5.2 图的存储结构</h1>
<h2 id="_5-2-1-图的存储结构" tabindex="-1"><a class="header-anchor" href="#_5-2-1-图的存储结构" aria-hidden="true">#</a> 5.2.1 图的存储结构</h2>
<ul>
<li>①领接矩阵：顺序存储（一维数组存点的数据，二维数组存边的连接情况）(存储无向图、有向图)</li>
<li>②邻接表：顺序+链式存储（顺序存点的数据，链存连接该点的边）（存储有向图、无向图）</li>
<li>③十字链表：链式存储（存储有向图）</li>
<li>④邻接多重表：链式存储（存储无向图）</li>
</ul>
<figure><img src="/images/datastruct/1637936258196.png" alt="1637936258196" tabindex="0" loading="lazy"><figcaption>1637936258196</figcaption></figure>
<h2 id="_5-2-2-邻接矩阵法" tabindex="-1"><a class="header-anchor" href="#_5-2-2-邻接矩阵法" aria-hidden="true">#</a> 5.2.2 邻接矩阵法</h2>
<p><code v-pre>空间复杂度</code>=<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>O</mi><mo stretchy="false">(</mo><mi mathvariant="normal">∣</mi><mi>V</mi><msup><mi mathvariant="normal">∣</mi><mn>2</mn></msup></mrow><annotation encoding="application/x-tex">O(|V|^2</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1.0641em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">O</span><span class="mopen">(</span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.22222em;">V</span><span class="mord"><span class="mord">∣</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.8141em;"><span style="top:-3.063em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">2</span></span></span></span></span></span></span></span></span></span></span>，<code v-pre>适合存稠密图</code></p>
<p><code v-pre>无向图的邻接矩阵</code>是<code v-pre>对称矩阵</code>，可以<code v-pre>压缩存储</code>，见3.6</p>
<p><code v-pre>性质</code>：<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>A</mi></mrow><annotation encoding="application/x-tex">A</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal">A</span></span></span></span>为图<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>G</mi></mrow><annotation encoding="application/x-tex">G</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal">G</span></span></span></span>的邻接矩阵，则<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msup><mi>A</mi><mi>n</mi></msup></mrow><annotation encoding="application/x-tex">A^n</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord"><span class="mord mathnormal">A</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.6644em;"><span style="top:-3.063em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight">n</span></span></span></span></span></span></span></span></span></span></span>的元素<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msup><mi>A</mi><mi>n</mi></msup><mo stretchy="false">[</mo><mi>i</mi><mo stretchy="false">]</mo><mo stretchy="false">[</mo><mi>j</mi><mo stretchy="false">]</mo></mrow><annotation encoding="application/x-tex">A^n[i][j]</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord"><span class="mord mathnormal">A</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.6644em;"><span style="top:-3.063em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight">n</span></span></span></span></span></span></span></span><span class="mopen">[</span><span class="mord mathnormal">i</span><span class="mclose">]</span><span class="mopen">[</span><span class="mord mathnormal" style="margin-right:0.05724em;">j</span><span class="mclose">]</span></span></span></span>=<code v-pre>顶点i到顶点j的长度为n的路径的数目</code></p>
<p><code v-pre>计算度、入度、出度</code>：必须遍历对应的行或列。
<code v-pre>找相邻的边</code>：必须遍历对应的行或列。</p>
<h3 id="普通图的领接矩阵法" tabindex="-1"><a class="header-anchor" href="#普通图的领接矩阵法" aria-hidden="true">#</a> 普通图的领接矩阵法：</h3>
<figure><img src="/images/datastruct/1637846244394.png" alt="1637846244394" tabindex="0" loading="lazy"><figcaption>1637846244394</figcaption></figure>
<div class="language-c line-numbers-mode" data-ext="c"><pre v-pre class="language-c"><code><span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">define</span> <span class="token macro-name">MaxVertexNum</span> <span class="token expression"><span class="token number">100</span>                 </span><span class="token comment">//顶点数目最大值</span></span>
<span class="token keyword">typedef</span> <span class="token keyword">struct</span><span class="token punctuation">{</span>
    <span class="token keyword">char</span> Vex<span class="token punctuation">[</span>MaxVertexNum<span class="token punctuation">]</span><span class="token punctuation">;</span>              <span class="token comment">//顶点表：存每个点的数据</span>
    <span class="token keyword">int</span> Edge<span class="token punctuation">[</span>MaxVertexNum<span class="token punctuation">]</span><span class="token punctuation">[</span>MaxVertexNum<span class="token punctuation">]</span><span class="token punctuation">;</span><span class="token comment">//邻接矩阵，边表：存边的连接情况</span>
    <span class="token keyword">int</span> vexnum<span class="token punctuation">,</span> arcnum<span class="token punctuation">;</span>                  <span class="token comment">//图当前的顶点数和边数（弧数）</span>
<span class="token punctuation">}</span>MGraph<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>边可以是int，bool或枚举型变量。</p>
<h3 id="普通图的度、入度、出度" tabindex="-1"><a class="header-anchor" href="#普通图的度、入度、出度" aria-hidden="true">#</a> 普通图的度、入度、出度</h3>
<p>某点的度：某点的边数</p>
<p>无向图：
<code v-pre>第i个结点的度</code>=<code v-pre>第i行(第i列)</code>的<code v-pre>非零元素</code>个数。</p>
<p>有向图：
<code v-pre>第i个结点的出度</code>=<code v-pre>第i行</code>的<code v-pre>非零元素</code>个数。
<code v-pre>第i个结点的入度</code>=<code v-pre>第i列</code>的<code v-pre>非零元素</code>个数。
<code v-pre>第i个结点的度</code>=<code v-pre>第i行、第i列</code>的<code v-pre>非零元素</code>个数<code v-pre>之和</code>。</p>
<p>求顶点的度、入度、出度的<code v-pre>时间复杂度</code>=O(<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi mathvariant="normal">∣</mi><mi>V</mi><mi mathvariant="normal">∣</mi></mrow><annotation encoding="application/x-tex">|V|</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.22222em;">V</span><span class="mord">∣</span></span></span></span>)</p>
<h3 id="带权图的领接矩阵法" tabindex="-1"><a class="header-anchor" href="#带权图的领接矩阵法" aria-hidden="true">#</a> 带权图的领接矩阵法</h3>
<figure><img src="/images/datastruct/1637848061168.png" alt="1637848061168" tabindex="0" loading="lazy"><figcaption>1637848061168</figcaption></figure>
<div class="language-c line-numbers-mode" data-ext="c"><pre v-pre class="language-c"><code><span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">define</span> <span class="token macro-name">MaxVertexNum</span> <span class="token expression"><span class="token number">100</span>                 </span><span class="token comment">//顶点数目最大值</span></span>
<span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">define</span> <span class="token macro-name">INFINITY</span> <span class="token expression"><span class="token number">4294967295</span>              </span><span class="token comment">//宏定义常量“无穷”，4294967295为最大的int值</span></span>
<span class="token keyword">typedef</span> <span class="token keyword">char</span> VertexType<span class="token punctuation">;</span>                 <span class="token comment">//顶点的数据类型</span>
<span class="token keyword">typedef</span> <span class="token keyword">int</span> EdgeType<span class="token punctuation">;</span>                    <span class="token comment">//边的数据类型</span>
<span class="token keyword">typedef</span> <span class="token keyword">struct</span><span class="token punctuation">{</span>
    VertexType Vex<span class="token punctuation">[</span>MaxVertexNum<span class="token punctuation">]</span><span class="token punctuation">;</span>        <span class="token comment">//顶点表：存每个点的数据</span>
    EdgeType Edge<span class="token punctuation">[</span>MaxVertexNum<span class="token punctuation">]</span><span class="token punctuation">[</span>MaxVertexNum<span class="token punctuation">]</span><span class="token punctuation">;</span><span class="token comment">//邻接矩阵，边表：存边的连接情况</span>
    <span class="token keyword">int</span> vexnum<span class="token punctuation">,</span> arcnum<span class="token punctuation">;</span>                  <span class="token comment">//图当前的顶点数和边数（弧数）</span>
<span class="token punctuation">}</span>MGraph<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_5-2-3-邻接表法" tabindex="-1"><a class="header-anchor" href="#_5-2-3-邻接表法" aria-hidden="true">#</a> 5.2.3 邻接表法</h2>
<p><code v-pre>空间复杂度</code>：无向图为<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>O</mi><mo stretchy="false">(</mo><mi mathvariant="normal">∣</mi><mi>V</mi><mi mathvariant="normal">∣</mi><mo>+</mo><mn>2</mn><mi mathvariant="normal">∣</mi><mi>E</mi><mi mathvariant="normal">∣</mi><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">O(|V|+2|E|)</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">O</span><span class="mopen">(</span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.22222em;">V</span><span class="mord">∣</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">2∣</span><span class="mord mathnormal" style="margin-right:0.05764em;">E</span><span class="mord">∣</span><span class="mclose">)</span></span></span></span>，有向图为<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>O</mi><mo stretchy="false">(</mo><mi mathvariant="normal">∣</mi><mi>V</mi><mi mathvariant="normal">∣</mi><mo>+</mo><mi mathvariant="normal">∣</mi><mi>E</mi><mi mathvariant="normal">∣</mi><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">O(|V|+|E|)</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">O</span><span class="mopen">(</span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.22222em;">V</span><span class="mord">∣</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.05764em;">E</span><span class="mord">∣</span><span class="mclose">)</span></span></span></span>，<code v-pre>适合存稀疏图</code>
<code v-pre>表示方式不唯一</code></p>
<p>邻接矩阵降低了空间复杂度，但使操作不方便了：
<code v-pre>计算度、入度、出度</code>：计算有向图的度、入度不方便，其余很方便。</p>
<p><code v-pre>找相邻的边</code>：找有向图的入边不方便。</p>
<h3 id="图的类型描述" tabindex="-1"><a class="header-anchor" href="#图的类型描述" aria-hidden="true">#</a> 图的类型描述：</h3>
<p>与树的孩子表示法很像</p>
<figure><img src="/images/datastruct/1637934445539.jpg" alt="1637934445539" tabindex="0" loading="lazy"><figcaption>1637934445539</figcaption></figure>
<div class="language-c line-numbers-mode" data-ext="c"><pre v-pre class="language-c"><code><span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">define</span> <span class="token macro-name">MaxVertexNum</span> <span class="token expression"><span class="token number">100</span>       </span><span class="token comment">//顶点数目最大值</span></span>
<span class="token comment">//"边（弧）"</span>
<span class="token keyword">typedef</span> <span class="token keyword">struct</span> <span class="token class-name">ArcNode</span><span class="token punctuation">{</span>
    <span class="token keyword">int</span> adjvex<span class="token punctuation">;</span>                <span class="token comment">//边（弧）指向那个结点</span>
    <span class="token keyword">struct</span> <span class="token class-name">ArcNode</span> <span class="token operator">*</span>next<span class="token punctuation">;</span>      <span class="token comment">//指向下一条弧的指针</span>
    <span class="token comment">//InfoType info;           //边权值</span>
<span class="token punctuation">}</span>ArcNode<span class="token punctuation">;</span>
<span class="token comment">//"顶点"</span>
<span class="token keyword">typedef</span> <span class="token keyword">struct</span> <span class="token class-name">VNode</span><span class="token punctuation">{</span>
    VertexType data<span class="token punctuation">;</span>           <span class="token comment">//顶点数据</span>
    ArcNode <span class="token operator">*</span>first<span class="token punctuation">;</span>            <span class="token comment">//顶点指向的第一条边</span>
<span class="token punctuation">}</span>VNode<span class="token punctuation">,</span> AdjList<span class="token punctuation">[</span>MaxVertexNum<span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token comment">//用领接表存储图</span>
<span class="token keyword">typedef</span> <span class="token keyword">struct</span><span class="token punctuation">{</span>
    AdjList vertices<span class="token punctuation">;</span>          <span class="token comment">//顶点数组</span>
    <span class="token keyword">int</span> vernum<span class="token punctuation">,</span> arcnum<span class="token punctuation">;</span>        <span class="token comment">////图当前的顶点数和边数（弧数）</span>
<span class="token punctuation">}</span>ALGraph<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_5-2-4-十字链表法" tabindex="-1"><a class="header-anchor" href="#_5-2-4-十字链表法" aria-hidden="true">#</a> 5.2.4 十字链表法</h2>
<p><code v-pre>空间复杂度</code>：<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>O</mi><mo stretchy="false">(</mo><mi mathvariant="normal">∣</mi><mi>V</mi><mi mathvariant="normal">∣</mi><mo>+</mo><mi mathvariant="normal">∣</mi><mi>E</mi><mi mathvariant="normal">∣</mi><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">O(|V|+|E|)</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">O</span><span class="mopen">(</span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.22222em;">V</span><span class="mord">∣</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.05764em;">E</span><span class="mord">∣</span><span class="mclose">)</span></span></span></span>，与邻接表法一样</p>
<p>解决了邻接表法的找入边难的问题。</p>
<figure><img src="/images/datastruct/1637936499284.png" alt="1637936499284" tabindex="0" loading="lazy"><figcaption>1637936499284</figcaption></figure>
<h2 id="_5-2-5-邻接多重表" tabindex="-1"><a class="header-anchor" href="#_5-2-5-邻接多重表" aria-hidden="true">#</a> 5.2.5 邻接多重表</h2>
<p><code v-pre>空间复杂度</code>：<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>O</mi><mo stretchy="false">(</mo><mi mathvariant="normal">∣</mi><mi>V</mi><mi mathvariant="normal">∣</mi><mo>+</mo><mi mathvariant="normal">∣</mi><mi>E</mi><mi mathvariant="normal">∣</mi><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">O(|V|+|E|)</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">O</span><span class="mopen">(</span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.22222em;">V</span><span class="mord">∣</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.05764em;">E</span><span class="mord">∣</span><span class="mclose">)</span></span></span></span>，比邻接表法的<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>O</mi><mo stretchy="false">(</mo><mi mathvariant="normal">∣</mi><mi>V</mi><mi mathvariant="normal">∣</mi><mo>+</mo><mn>2</mn><mi mathvariant="normal">∣</mi><mi>E</mi><mi mathvariant="normal">∣</mi><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">O(|V|+2|E|)</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">O</span><span class="mopen">(</span><span class="mord">∣</span><span class="mord mathnormal" style="margin-right:0.22222em;">V</span><span class="mord">∣</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord">2∣</span><span class="mord mathnormal" style="margin-right:0.05764em;">E</span><span class="mord">∣</span><span class="mclose">)</span></span></span></span>好</p>
<p>解决了邻接表法存两遍边的空间浪费。</p>
<p>删除边、删除结点等操作很方便。</p>
<figure><img src="/images/datastruct/1637936777739.png" alt="1637936777739" tabindex="0" loading="lazy"><figcaption>1637936777739</figcaption></figure>
</div></template>


